/* ============================================
   CLINIC TEMPLATE — BILINGUAL DICTIONARY
   Indonesian (Primary) / English
   ============================================ */

const translations = {
    id: {
        /* -- Nav -- */
        nav_home: 'Beranda',
        nav_about: 'Tentang',
        nav_services: 'Layanan',
        nav_doctors: 'Dokter',
        nav_contact: 'Kontak',
        nav_appointment: 'Buat Janji',

        /* -- Home — Hero -- */
        hero_badge: '🏥 Klinik Terpercaya Sejak 2010',
        hero_title_1: 'Kesehatan Anda,',
        hero_title_2: 'Prioritas Kami',
        hero_title_3: 'Layanan Medis Profesional',
        hero_desc: 'Memberikan pelayanan kesehatan berkualitas dengan tenaga medis berpengalaman, fasilitas modern, dan pendekatan penuh perhatian untuk setiap pasien.',
        hero_btn_appointment: 'Buat Janji Online',
        hero_btn_services: 'Lihat Layanan',
        hero_stat_1_val: '15+',
        hero_stat_1_label: 'Tahun Pengalaman',
        hero_stat_2_val: '25.000+',
        hero_stat_2_label: 'Pasien Dilayani',
        hero_stat_3_val: '20+',
        hero_stat_3_label: 'Dokter Spesialis',
        hero_float_1_val: '4.9',
        hero_float_1_label: 'Rating Google',
        hero_float_2_val: '24/7',
        hero_float_2_label: 'UGD Siaga',

        /* -- Home — Services Overview -- */
        services_label: 'Layanan Kami',
        services_title: 'Layanan Medis Terbaik',
        services_subtitle: 'Kami menyediakan berbagai layanan kesehatan dengan standar internasional dan pelayanan yang penuh perhatian.',
        service_1_title: 'Pemeriksaan Umum',
        service_1_desc: 'Konsultasi dan pemeriksaan kesehatan menyeluruh oleh dokter umum berpengalaman.',
        service_2_title: 'Spesialis Anak',
        service_2_desc: 'Perawatan khusus untuk kesehatan buah hati Anda dari lahir hingga remaja.',
        service_3_title: 'Spesialis Gigi',
        service_3_desc: 'Perawatan gigi lengkap mulai dari pembersihan, tambal, hingga pemasangan kawat.',
        service_4_title: 'Laboratrium',
        service_4_desc: 'Pemeriksaan laboratorium dengan peralatan modern dan hasil akurat cepat.',
        service_5_title: 'Spesialis Mata',
        service_5_desc: 'Pemeriksaan mata lengkap, pengobatan, dan resep kacamata dari ahli optometri.',
        service_6_title: 'USG & Radiologi',
        service_6_desc: 'Pemeriksaan USG, rontgen, dan pencitraan medis dengan teknologi terkini.',
        service_link: 'Selengkapnya →',

        /* -- Home — Stats -- */
        stat_1_val: '15+',
        stat_1_label: 'Tahun Pengalaman',
        stat_2_val: '25.000+',
        stat_2_label: 'Pasien Dilayani',
        stat_3_val: '20+',
        stat_3_label: 'Dokter Spesialis',
        stat_4_val: '98%',
        stat_4_label: 'Kepuasan Pasien',

        /* -- Home — Featured Doctors -- */
        doctors_label: 'Dokter Kami',
        doctors_title: 'Tim Dokter Profesional',
        doctors_subtitle: 'Dokter-dokter terbaik dan berpengalaman siap melayani kesehatan Anda.',
        doctor_1_name: 'dr. Anita Sari, Sp.PD',
        doctor_1_spec: 'Spesialis Penyakit Dalam',
        doctor_1_bio: 'Berpengalaman 15 tahun dalam diagnostik dan terapi penyakit dalam.',
        doctor_1_sched: 'Sen-Jum • 08:00-14:00',
        doctor_2_name: 'drg. Budi Hartono',
        doctor_2_spec: 'Dokter Gigi & Mulut',
        doctor_2_bio: 'Ahli perawatan gigi estetik dan bedah mulut dengan pendekatan gentle.',
        doctor_2_sched: 'Sen-Sab • 09:00-16:00',
        doctor_3_name: 'dr. Citra Melani, Sp.A',
        doctor_3_spec: 'Spesialis Anak',
        doctor_3_bio: 'Pediatri bersertifikasi dengan keahlian di tumbuh kembang anak.',
        doctor_3_sched: 'Sel-Sab • 10:00-17:00',
        doctors_all: 'Lihat Semua Dokter →',

        /* -- Home — Testimonials -- */
        testimonials_label: 'Testimoni',
        testimonials_title: 'Kata Pasien Kami',
        testimonials_subtitle: 'Pendapat jujur dari pasien yang telah merasakan pelayanan kami.',
        testi_1_text: 'Pelayanannya sangat ramah dan profesional. Dokternya sabar menjelaskan kondisi kesehatan saya. Fasilitas klinik juga bersih dan nyaman.',
        testi_1_name: 'Ibu Diana Kusuma',
        testi_1_role: 'Pasien Penyakit Dalam',
        testi_2_text: 'Anak saya diperiksa oleh dr. Citra dan hasilnya sangat memuaskan. Penanganannya cepat dan anak saya tidak takut sama sekali.',
        testi_2_name: 'Bapak Eko Prasetyo',
        testi_2_role: 'Orang Tua Pasien Anak',
        testi_3_text: 'Saya rutin kontrol gigi di sini. drg. Budi sangat teliti dan gentle. Hasil perawatannya selalu memuaskan. Highly recommended!',
        testi_3_name: 'Mbak Fitria Sari',
        testi_3_role: 'Pasien Gigi & Mulut',

        /* -- Home — CTA -- */
        cta_title: 'Jaga Kesehatan Anda Sekarang',
        cta_text: 'Jangan tunda untuk memeriksakan diri. Buat janji temu online dan dapatkan pelayanan terbaik dari tim medis kami.',
        cta_btn_primary: 'Buat Janji Sekarang',
        cta_btn_secondary: '💬 Chat WhatsApp',

        /* -- About Page -- */
        about_label: 'Tentang Kami',
        about_title: 'Klinik Terpercaya untuk Keluarga',
        about_subtitle: 'Didirikan dengan visi memberikan pelayanan kesehatan terbaik yang terjangkau untuk seluruh masyarakat.',
        about_story_title: '📖 Cerita Kami',
        about_story_text: 'KlinikSehat didirikan pada tahun 2010 oleh sekelompok dokter yang memiliki visi yang sama: menyediakan layanan kesehatan berkualitas yang terjangkau bagi seluruh lapisan masyarakat. Bermula dari klinik kecil di Jakarta, kami terus berkembang hingga memiliki fasilitas modern dan tim dokter spesialis yang lengkap.',
        about_vision_title: '🎯 Visi',
        about_vision_text: 'Menjadi klinik pilihan utama masyarakat Indonesia dalam memberikan pelayanan kesehatan yang berkualitas, terjangkau, dan penuh perhatian.',
        about_mission_title: '🧭 Misi',
        about_mission_1: 'Memberikan pelayanan medis berstandar tinggi',
        about_mission_2: 'Mengutamakan keselamatan dan kenyamanan pasien',
        about_mission_3: 'Menyediakan tenaga medis yang profesional dan berlisensi',
        about_mission_4: 'Menggunakan teknologi medis terkini',
        about_mission_5: 'Membangun hubungan kepercayaan jangka panjang',
        about_timeline_title: 'Perjalanan Kami',
        about_tl_1_year: '2010',
        about_tl_1_title: 'Klinik Pertama Dibuka',
        about_tl_1_desc: 'Memulai perjalanan dengan klinik umum pertama di Jakarta Selatan.',
        about_tl_2_year: '2014',
        about_tl_2_title: 'Layanan Spesialis',
        about_tl_2_desc: 'Menambah layanan spesialis anak, gigi, dan penyakit dalam.',
        about_tl_3_year: '2018',
        about_tl_3_title: 'Fasilitas Modern',
        about_tl_3_desc: 'Renovasi total dengan peralatan medis berstandar internasional.',
        about_tl_4_year: '2022',
        about_tl_4_title: 'Digitalisasi',
        about_tl_4_desc: 'Meluncurkan sistem booking online dan rekam medis elektronik.',
        about_tl_5_year: '2025',
        about_tl_5_title: 'Cabang Baru',
        about_tl_5_desc: 'Membuka 2 cabang baru untuk menjangkau lebih banyak masyarakat.',
        about_accreditation: 'Terakreditasi & Terdaftar',

        /* -- Services Page -- */
        services_page_label: 'Layanan Kami',
        services_page_title: 'Layanan Kesehatan Lengkap',
        services_page_subtitle: 'Kami menyediakan berbagai layanan medis untuk memenuhi kebutuhan kesehatan Anda dan keluarga.',
        svc_detail_1_title: 'Pemeriksaan Umum',
        svc_detail_1_desc: 'Layanan konsultasi dan pemeriksaan oleh dokter umum berpengalaman. Meliputi anamnesis lengkap, pemeriksaan fisik, diagnosa, dan pemberian resep serta edukasi kesehatan.',
        svc_detail_1_sched: '⏰ Senin - Sabtu • 07:00 - 21:00',
        svc_detail_2_title: 'Spesialis Penyakit Dalam',
        svc_detail_2_desc: 'Penanganan gangguan organ dalam seperti jantung, paru-paru, ginjal, hati, dan sistem pencernaan oleh dokter internis bersertifikasi.',
        svc_detail_2_sched: '⏰ Senin - Jumat • 08:00 - 14:00',
        svc_detail_3_title: 'Spesialis Anak',
        svc_detail_3_desc: 'Perawatan kesehatan komprehensif untuk bayi, anak, dan remaja. Termasuk imunisasi, pemeriksaan tumbuh kembang, dan pengobatan penyakit anak.',
        svc_detail_3_sched: '⏰ Selasa - Sabtu • 10:00 - 17:00',
        svc_detail_4_title: 'Dokter Gigi & Mulut',
        svc_detail_4_desc: 'Layanan dental lengkap: pembersihan karang gigi, tambal gigi, cabut gigi, perawatan saluran akar, veneer, dan pemasangan kawat gigi.',
        svc_detail_4_sched: '⏰ Senin - Sabtu • 09:00 - 16:00',
        svc_detail_5_title: 'Spesialis Mata',
        svc_detail_5_desc: 'Pemeriksaan refraksi, pengobatan infeksi mata, glaukoma, katarak, dan resep kacamata oleh dokter spesialis mata berpengalaman.',
        svc_detail_5_sched: '⏰ Senin - Kamis • 09:00 - 15:00',
        svc_detail_6_title: 'Laboratorium',
        svc_detail_6_desc: 'Tes darah, urinalisis, profil lipid, gula darah, fungsi hati, fungsi ginjal, dan berbagai pemeriksaan lab dengan hasil cepat dan akurat.',
        svc_detail_6_sched: '⏰ Setiap Hari • 06:00 - 20:00',
        svc_detail_7_title: 'USG & Radiologi',
        svc_detail_7_desc: 'Pemeriksaan USG kehamilan, USG abdomen, rontgen thorax, dan pencitraan medis lainnya dengan peralatan digital berteknologi tinggi.',
        svc_detail_7_sched: '⏰ Senin - Sabtu • 08:00 - 17:00',
        svc_detail_8_title: 'Fisioterapi',
        svc_detail_8_desc: 'Program rehabilitasi medis untuk pemulihan pasca operasi, cedera olahraga, nyeri sendi, dan gangguan otot dengan terapi terukur.',
        svc_detail_8_sched: '⏰ Senin - Jumat • 09:00 - 16:00',

        /* -- Doctors Page -- */
        doctors_page_label: 'Tim Medis',
        doctors_page_title: 'Dokter Kami',
        doctors_page_subtitle: 'Tim dokter profesional dan berpengalaman yang berkomitmen untuk kesehatan Anda.',

        /* -- Contact Page -- */
        contact_label: 'Hubungi Kami',
        contact_title: 'Hubungi Klinik Kami',
        contact_subtitle: 'Kami siap membantu Anda. Hubungi kami melalui telepon, WhatsApp, email, atau kunjungi langsung.',
        contact_address_title: 'Alamat Klinik',
        contact_address: 'Jl. Kesehatan No. 88, Kebayoran Baru, Jakarta Selatan 12160',
        contact_phone_title: 'Telepon / WhatsApp',
        contact_phone: '+62 21 7890 1234',
        contact_email_title: 'Email',
        contact_email: 'info@kliniksehat.id',
        contact_hours_title: '⏰ Jam Operasional',
        contact_hours_weekday: 'Senin - Jumat',
        contact_hours_weekday_time: '07:00 - 21:00',
        contact_hours_saturday: 'Sabtu',
        contact_hours_saturday_time: '08:00 - 17:00',
        contact_hours_sunday: 'Minggu',
        contact_hours_sunday_time: '09:00 - 14:00',
        contact_emergency: '🚨 Gawat Darurat 24 Jam',
        contact_emergency_number: '(021) 119',
        contact_form_title: 'Kirim Pesan',
        contact_form_name: 'Nama Lengkap',
        contact_form_phone: 'No. Telepon',
        contact_form_email_field: 'Email',
        contact_form_subject: 'Subjek',
        contact_form_message: 'Pesan Anda',
        contact_form_submit: 'Kirim Pesan',

        /* -- Appointment Page -- */
        appt_label: 'Reservasi',
        appt_title: 'Buat Janji Temu',
        appt_subtitle: 'Reservasi jadwal kunjungan Anda secara online. Mudah, cepat, dan tanpa antri.',
        appt_form_title: '📅 Formulir Pendaftaran',
        appt_name: 'Nama Pasien',
        appt_phone: 'No. WhatsApp',
        appt_email: 'Email',
        appt_service: 'Pilih Layanan',
        appt_service_opt_1: 'Pemeriksaan Umum',
        appt_service_opt_2: 'Spesialis Penyakit Dalam',
        appt_service_opt_3: 'Spesialis Anak',
        appt_service_opt_4: 'Dokter Gigi',
        appt_service_opt_5: 'Spesialis Mata',
        appt_service_opt_6: 'Laboratorium',
        appt_service_opt_7: 'USG & Radiologi',
        appt_service_opt_8: 'Fisioterapi',
        appt_doctor: 'Pilih Dokter',
        appt_doctor_opt_1: 'dr. Anita Sari, Sp.PD',
        appt_doctor_opt_2: 'drg. Budi Hartono',
        appt_doctor_opt_3: 'dr. Citra Melani, Sp.A',
        appt_doctor_opt_4: 'dr. Reza Adriansyah, Sp.M',
        appt_doctor_opt_5: 'Dokter Umum Yang Bertugas',
        appt_date: 'Tanggal Kunjungan',
        appt_time: 'Waktu Preferensi',
        appt_time_opt_1: 'Pagi (08:00-12:00)',
        appt_time_opt_2: 'Siang (12:00-15:00)',
        appt_time_opt_3: 'Sore (15:00-18:00)',
        appt_notes: 'Keluhan / Catatan',
        appt_submit: 'Kirim Reservasi',
        appt_info_1: '📞 Konfirmasi via WhatsApp',
        appt_info_2: '💳 Terima BPJS & Asuransi',
        appt_info_3: '🕐 Tanpa antri',
        appt_info_4: '📋 Bisa reschedule',

        /* -- Footer -- */
        footer_brand_desc: 'Klinik kesehatan terpercaya dengan pelayanan profesional dan fasilitas modern untuk seluruh keluarga Indonesia sejak 2010.',
        footer_links: 'Menu',
        footer_services: 'Layanan',
        footer_contact: 'Kontak',
        footer_privacy: 'Kebijakan Privasi',
        footer_terms: 'Syarat & Ketentuan',
        footer_copyright: '© 2026 KlinikSehat. Hak cipta dilindungi.'
    },

    en: {
        nav_home: 'Home',
        nav_about: 'About',
        nav_services: 'Services',
        nav_doctors: 'Doctors',
        nav_contact: 'Contact',
        nav_appointment: 'Book Now',

        hero_badge: '🏥 Trusted Clinic Since 2010',
        hero_title_1: 'Your Health,',
        hero_title_2: 'Our Priority',
        hero_title_3: 'Professional Medical Services',
        hero_desc: 'Providing quality healthcare with experienced medical professionals, modern facilities, and a caring approach for every patient.',
        hero_btn_appointment: 'Book Appointment',
        hero_btn_services: 'Our Services',
        hero_stat_1_val: '15+',
        hero_stat_1_label: 'Years Experience',
        hero_stat_2_val: '25,000+',
        hero_stat_2_label: 'Patients Served',
        hero_stat_3_val: '20+',
        hero_stat_3_label: 'Specialist Doctors',
        hero_float_1_val: '4.9',
        hero_float_1_label: 'Google Rating',
        hero_float_2_val: '24/7',
        hero_float_2_label: 'Emergency',

        services_label: 'Our Services',
        services_title: 'Best Medical Services',
        services_subtitle: 'We provide various health services with international standards and caring attention.',
        service_1_title: 'General Check-Up',
        service_1_desc: 'Comprehensive health consultation and examination by experienced general practitioners.',
        service_2_title: 'Pediatric Care',
        service_2_desc: 'Special healthcare for your children from birth through adolescence.',
        service_3_title: 'Dental Care',
        service_3_desc: 'Complete dental services from cleaning, fillings, to orthodontics.',
        service_4_title: 'Laboratory',
        service_4_desc: 'Lab tests with modern equipment and quick, accurate results.',
        service_5_title: 'Ophthalmology',
        service_5_desc: 'Complete eye exams, treatments, and prescriptions from expert optometrists.',
        service_6_title: 'USG & Radiology',
        service_6_desc: 'USG, X-ray, and medical imaging with cutting-edge technology.',
        service_link: 'Learn More →',

        stat_1_val: '15+',
        stat_1_label: 'Years Experience',
        stat_2_val: '25,000+',
        stat_2_label: 'Patients Served',
        stat_3_val: '20+',
        stat_3_label: 'Specialist Doctors',
        stat_4_val: '98%',
        stat_4_label: 'Patient Satisfaction',

        doctors_label: 'Our Doctors',
        doctors_title: 'Professional Medical Team',
        doctors_subtitle: 'Experienced and dedicated doctors ready to serve your health needs.',
        doctor_1_name: 'dr. Anita Sari, Sp.PD',
        doctor_1_spec: 'Internal Medicine',
        doctor_1_bio: '15 years of experience in internal medicine diagnostics and therapy.',
        doctor_1_sched: 'Mon-Fri • 08:00-14:00',
        doctor_2_name: 'drg. Budi Hartono',
        doctor_2_spec: 'Dental & Oral',
        doctor_2_bio: 'Expert in aesthetic dentistry and oral surgery with a gentle approach.',
        doctor_2_sched: 'Mon-Sat • 09:00-16:00',
        doctor_3_name: 'dr. Citra Melani, Sp.A',
        doctor_3_spec: 'Pediatrician',
        doctor_3_bio: 'Board-certified pediatrician with expertise in child development.',
        doctor_3_sched: 'Tue-Sat • 10:00-17:00',
        doctors_all: 'View All Doctors →',

        testimonials_label: 'Testimonials',
        testimonials_title: 'What Patients Say',
        testimonials_subtitle: 'Honest reviews from patients who have experienced our services.',
        testi_1_text: 'The service is very friendly and professional. The doctor patiently explained my condition. The clinic facilities are also clean and comfortable.',
        testi_1_name: 'Mrs. Diana Kusuma',
        testi_1_role: 'Internal Medicine Patient',
        testi_2_text: 'My child was examined by dr. Citra and the result was very satisfying. Fast treatment and my child was not scared at all.',
        testi_2_name: 'Mr. Eko Prasetyo',
        testi_2_role: 'Pediatric Patient\'s Parent',
        testi_3_text: 'I regularly check my teeth here. drg. Budi is very thorough and gentle. Treatment results are always satisfying. Highly recommended!',
        testi_3_name: 'Ms. Fitria Sari',
        testi_3_role: 'Dental Patient',

        cta_title: 'Take Care of Your Health Now',
        cta_text: 'Don\'t delay your checkup. Book an appointment online and get the best service from our medical team.',
        cta_btn_primary: 'Book Now',
        cta_btn_secondary: '💬 Chat WhatsApp',

        about_label: 'About Us',
        about_title: 'Trusted Family Clinic',
        about_subtitle: 'Founded with a vision to provide the best affordable healthcare for all communities.',
        about_story_title: '📖 Our Story',
        about_story_text: 'KlinikSehat was founded in 2010 by a group of doctors who shared a vision: providing quality, affordable healthcare for all. Starting from a small clinic in Jakarta, we\'ve grown to have modern facilities and a full team of specialist doctors.',
        about_vision_title: '🎯 Vision',
        about_vision_text: 'To become the primary healthcare choice for Indonesian communities by providing quality, affordable, and caring medical services.',
        about_mission_title: '🧭 Mission',
        about_mission_1: 'Provide high-standard medical services',
        about_mission_2: 'Prioritize patient safety and comfort',
        about_mission_3: 'Employ professional and licensed medical staff',
        about_mission_4: 'Utilize cutting-edge medical technology',
        about_mission_5: 'Build long-term trusted relationships',
        about_timeline_title: 'Our Journey',
        about_tl_1_year: '2010',
        about_tl_1_title: 'First Clinic Opened',
        about_tl_1_desc: 'Started our journey with the first general clinic in South Jakarta.',
        about_tl_2_year: '2014',
        about_tl_2_title: 'Specialist Services',
        about_tl_2_desc: 'Added pediatric, dental, and internal medicine specialist services.',
        about_tl_3_year: '2018',
        about_tl_3_title: 'Modern Facilities',
        about_tl_3_desc: 'Complete renovation with international-standard medical equipment.',
        about_tl_4_year: '2022',
        about_tl_4_title: 'Digitalization',
        about_tl_4_desc: 'Launched online booking system and electronic medical records.',
        about_tl_5_year: '2025',
        about_tl_5_title: 'New Branches',
        about_tl_5_desc: 'Opened 2 new branches to reach more communities.',
        about_accreditation: 'Accredited & Registered',

        services_page_label: 'Our Services',
        services_page_title: 'Complete Healthcare Services',
        services_page_subtitle: 'We provide various medical services to meet the health needs of you and your family.',
        svc_detail_1_title: 'General Check-Up',
        svc_detail_1_desc: 'Consultation and examination by experienced general practitioners. Includes complete history, physical exam, diagnosis, prescription, and health education.',
        svc_detail_1_sched: '⏰ Mon-Sat • 07:00-21:00',
        svc_detail_2_title: 'Internal Medicine',
        svc_detail_2_desc: 'Treatment of internal organ disorders including heart, lungs, kidneys, liver, and digestive system by certified internists.',
        svc_detail_2_sched: '⏰ Mon-Fri • 08:00-14:00',
        svc_detail_3_title: 'Pediatric Care',
        svc_detail_3_desc: 'Comprehensive healthcare for infants, children, and adolescents. Including immunization, growth monitoring, and pediatric treatments.',
        svc_detail_3_sched: '⏰ Tue-Sat • 10:00-17:00',
        svc_detail_4_title: 'Dental & Oral Care',
        svc_detail_4_desc: 'Complete dental services: scaling, fillings, extractions, root canals, veneers, and orthodontics.',
        svc_detail_4_sched: '⏰ Mon-Sat • 09:00-16:00',
        svc_detail_5_title: 'Ophthalmology',
        svc_detail_5_desc: 'Refraction testing, eye infection treatment, glaucoma, cataracts, and prescriptions by experienced ophthalmologists.',
        svc_detail_5_sched: '⏰ Mon-Thu • 09:00-15:00',
        svc_detail_6_title: 'Laboratory',
        svc_detail_6_desc: 'Blood tests, urinalysis, lipid profile, blood sugar, liver & kidney function, and various lab tests with fast and accurate results.',
        svc_detail_6_sched: '⏰ Daily • 06:00-20:00',
        svc_detail_7_title: 'USG & Radiology',
        svc_detail_7_desc: 'Pregnancy ultrasound, abdominal USG, chest X-ray, and other medical imaging with high-tech digital equipment.',
        svc_detail_7_sched: '⏰ Mon-Sat • 08:00-17:00',
        svc_detail_8_title: 'Physiotherapy',
        svc_detail_8_desc: 'Medical rehabilitation programs for post-surgery recovery, sports injuries, joint pain, and muscle disorders with measured therapy.',
        svc_detail_8_sched: '⏰ Mon-Fri • 09:00-16:00',

        doctors_page_label: 'Medical Team',
        doctors_page_title: 'Our Doctors',
        doctors_page_subtitle: 'Professional and experienced medical team committed to your health.',

        contact_label: 'Contact Us',
        contact_title: 'Contact Our Clinic',
        contact_subtitle: 'We\'re here to help. Reach us by phone, WhatsApp, email, or visit in person.',
        contact_address_title: 'Clinic Address',
        contact_address: 'Jl. Kesehatan No. 88, Kebayoran Baru, South Jakarta 12160',
        contact_phone_title: 'Phone / WhatsApp',
        contact_phone: '+62 21 7890 1234',
        contact_email_title: 'Email',
        contact_email: 'info@kliniksehat.id',
        contact_hours_title: '⏰ Operating Hours',
        contact_hours_weekday: 'Monday - Friday',
        contact_hours_weekday_time: '07:00 - 21:00',
        contact_hours_saturday: 'Saturday',
        contact_hours_saturday_time: '08:00 - 17:00',
        contact_hours_sunday: 'Sunday',
        contact_hours_sunday_time: '09:00 - 14:00',
        contact_emergency: '🚨 24-Hour Emergency',
        contact_emergency_number: '(021) 119',
        contact_form_title: 'Send Message',
        contact_form_name: 'Full Name',
        contact_form_phone: 'Phone Number',
        contact_form_email_field: 'Email',
        contact_form_subject: 'Subject',
        contact_form_message: 'Your Message',
        contact_form_submit: 'Send Message',

        appt_label: 'Reservation',
        appt_title: 'Book an Appointment',
        appt_subtitle: 'Schedule your visit online. Easy, fast, and no queues.',
        appt_form_title: '📅 Registration Form',
        appt_name: 'Patient Name',
        appt_phone: 'WhatsApp Number',
        appt_email: 'Email',
        appt_service: 'Choose Service',
        appt_service_opt_1: 'General Check-Up',
        appt_service_opt_2: 'Internal Medicine',
        appt_service_opt_3: 'Pediatric Care',
        appt_service_opt_4: 'Dental Care',
        appt_service_opt_5: 'Ophthalmology',
        appt_service_opt_6: 'Laboratory',
        appt_service_opt_7: 'USG & Radiology',
        appt_service_opt_8: 'Physiotherapy',
        appt_doctor: 'Choose Doctor',
        appt_doctor_opt_1: 'dr. Anita Sari, Sp.PD',
        appt_doctor_opt_2: 'drg. Budi Hartono',
        appt_doctor_opt_3: 'dr. Citra Melani, Sp.A',
        appt_doctor_opt_4: 'dr. Reza Adriansyah, Sp.M',
        appt_doctor_opt_5: 'On-Duty General Practitioner',
        appt_date: 'Visit Date',
        appt_time: 'Preferred Time',
        appt_time_opt_1: 'Morning (08:00-12:00)',
        appt_time_opt_2: 'Afternoon (12:00-15:00)',
        appt_time_opt_3: 'Evening (15:00-18:00)',
        appt_notes: 'Symptoms / Notes',
        appt_submit: 'Submit Reservation',
        appt_info_1: '📞 Confirmed via WhatsApp',
        appt_info_2: '💳 Accepts BPJS & Insurance',
        appt_info_3: '🕐 No waiting in line',
        appt_info_4: '📋 Reschedulable',

        footer_brand_desc: 'Trusted health clinic with professional services and modern facilities for all Indonesian families since 2010.',
        footer_links: 'Menu',
        footer_services: 'Services',
        footer_contact: 'Contact',
        footer_privacy: 'Privacy Policy',
        footer_terms: 'Terms & Conditions',
        footer_copyright: '© 2026 KlinikSehat. All rights reserved.'
    }
};
